@MyReactApp.Server_HostAddress = http://localhost:5120

GET {{MyReactApp.Server_HostAddress}}/weatherforecast/
Accept: application/json

###

GET {{MyReactApp.Server_HostAddress}}/product/
Accept: application/json